#!/bin/zsh

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

yabai -m config window_shadow  float
yabai -m config window_topmost on

yabai -m config layout         bsp
yabai -m config top_padding    5
yabai -m config bottom_padding 5
yabai -m config left_padding   5
yabai -m config right_padding  5
yabai -m config window_gap     5

yabai -m config --space 2 layout float

yabai -m rule --add app=Emacs manage=on
yabai -m rule --add app="System Preferences" manage=off
