#!/bin/sh

bspc monitor eDP-1 -d term web code music 5 6
bspc monitor DP-1  -d 7 8 9 0

bspc config border_width 0
bspc config window_gap   5

bspc config split_ratio        0.52
bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc rule -a Emacs state=tiled

$HOME/.config/polybar/launch.sh
