#!/bin/sh

bspc monitor DP-1 -d term web code music
bspc monitor DP-2 -d 5 6 7 8
bspc monitor DVI-1-0 -d 9 0

bspc config border_width 0
bspc config window_gap   5

bspc config split_ratio        0.52
bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc rule -a Emacs state=tiled

$HOME/.config/polybar/launch.sh
