#!/bin/sh

bspc monitor eDP-1 -d term web code music
bspc monitor DP-1  -d 5 6

bspc config border_width 0
bspc config window_gap   10

bspc config split_ratio        0.52
bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc rule -a Firefox desktop='web'
bspc rule -a Emacs   desktop='code' state=tiled

$HOME/.config/polybar/launch.sh
