#!/usr/bin/bash

case $1 in
  -l|--left) 
    xrandr --output DP-1 --left-of eDP-1 --auto;;
  -r|--right)
    xrandr --output DP-1 --right-of eDP-1 --auto;;
  -o|--off)
    xrandr --output DP-1 --off --auto;;
  -t|--rotate)
    xrandr --output DP-1 --rotate left --right-of eDP-1 --auto;;
  --reload);;
  *)
    echo <<- EOF
hdmi: Simple wrapper around xrandr to set the external display
      appropriately, with the options mostly premade.

  Options:
    -l,--left       Screen to the left of main.
    -r,--right      Screen to the right of main.
    -o,--off        Turn the other screen off.
    -r,--rotate     Rotate the screen left.
    --reload        Only reload the session.
EOF
exit 0;;
esac

~/.config/bspwm/bspwmrc >/dev/null 2>&1 &
~/.fehbg >/dev/null 2>&1

