#!/bin/sh
lock() {
  $HOME/.local/bin/betterlock -$1 blur
}

case "$1" in
  lock)
    lock l
    ;;
  logout)
    i3-msg exit
    ;;
  suspend)
    lock s
    ;;
  hibernate)
    lock && systemctl hibernate
    ;;
  reboot)
    systemctl reboot
    ;;
  shutdown)
    systemctl poweroff
    ;;
  *)
    echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
    exit 2
esac

exit 0
